version: '3'

services: 
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/dev/Dockerfile
    volumes:
      - ./backend:/backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on: 
      - db
    env_file:
      - ./backend/.env
    networks:
      - djangonetwork
  db:
    image: postgres:13.1-alpine
    env_file:
      - ./backend/.env
    networks:
      - djangonetwork

volumes:
  static_volume: {}

networks:
  djangonetwork:
    driver: bridge