# Generated by Django 3.2.3 on 2021-06-03 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 8, 39, 0, 389234)),
        ),
    ]
