# Generated by Django 3.2.3 on 2021-06-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_pay_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pay_day',
            field=models.DateTimeField(default=None),
        ),
    ]
