# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v2
    - name: Install Docker-compose
      run: |
        pip install docker-compose
    - name: Test with Django test
      run: |
        docker-compose -f docker-compose-dev.yml run --rm backend sh -c "python manage.py wait_for_db && python manage.py test && flake8"

    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose up -d
    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'
    - name: Check running containers
      run: docker ps
    - name: Run test suite
      run: docker exec backend test
